apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tanzu-java-web-app
  annotations:
    github.com/project-slug: kavianba/tanzu-java-web-app
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/part-of=tanzu-java-web-ap'
spec:
  type: service
  lifecycle: production
  owner: default-team
